# Generated by Django 6.0.2 on 2026-03-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_account_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
    ]
