# Generated by Django 6.0.2 on 2026-03-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction_is_transfer_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_transfer',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10),
        ),
    ]
