# Generated by Django 6.0.2 on 2026-03-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_transaction_is_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reason',
            field=models.CharField(blank=True, default='', help_text='Specific reason for this transaction (e.g. Spotify subscription, Movie tickets)', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], max_length=10),
        ),
    ]
