# Generated by Django 6.0.2 on 2026-03-06 04:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_pipeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiinsight',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Insight', 'verbose_name_plural': 'AI Insights'},
        ),
        migrations.AlterModelOptions(
            name='aipreferences',
            options={'verbose_name': 'AI Preference', 'verbose_name_plural': 'AI Preferences'},
        ),
        migrations.RemoveField(
            model_name='aiinsight',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='aiinsight',
            name='estimated_monthly_saving',
        ),
        migrations.RemoveField(
            model_name='aiinsight',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='aiinsight',
            name='next_step',
        ),
        migrations.RemoveField(
            model_name='aiinsight',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='aipreferences',
            name='excluded_merchants',
        ),
        migrations.RemoveField(
            model_name='aipreferences',
            name='monthly_saving_goal',
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='days',
            field=models.PositiveIntegerField(default=90, help_text='Look-back window used when generating this insight.'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='payload',
            field=models.JSONField(default=dict, help_text='Full or summarised orchestrator payload (JSON-serialisable).'),
        ),
        migrations.AddField(
            model_name='aipreferences',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='action',
            field=models.CharField(choices=[('draft_pipeline_output', 'Draft Pipeline Output'), ('final_insight', 'Final Insight')], default='draft_pipeline_output', max_length=64),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aipreferences',
            name='ai_enabled',
            field=models.BooleanField(default=True, help_text="Allow the AI pipeline to process this user's data."),
        ),
        migrations.AlterField(
            model_name='aipreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
