# Generated by Django 6.0.2 on 2026-03-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_pipeline', '0002_alter_aiinsight_options_alter_aipreferences_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiinsight',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='aipreferences',
            options={},
        ),
        migrations.RemoveField(
            model_name='aipreferences',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aipreferences',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='confidence',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='estimated_monthly_saving',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='next_step',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='days',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='aipreferences',
            name='ai_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
