# Generated by Django 6.0.2 on 2026-03-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_pipeline', '0003_alter_aiinsight_options_alter_aipreferences_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='feedback',
            field=models.CharField(blank=True, choices=[('accept', 'accept'), ('reject', 'reject')], max_length=10, null=True),
        ),
    ]
